### PR TITLE
Apple website clone - Completed

### PR DESCRIPTION
**Pull request by ikraamg**
Live Preview Link: https://rawcdn.githack.com/ikraamg/apple.com-clone/24cb6172e87b2014b595c5be86e82cbe95421a4c/index.html

*EDIT after review: It seems like the bug was only present in Mozilla browser due to the flexbox child not working with flex:1 and needed to be changed to flex: auto*

In this project:
-Created an HTML structure of the page and styled it with CSS Grid and Flexbox and Floats.

Steps:
-Created a Navbar
-Created a main section with the core content and images
-Created an "ad-grid" section
-Created a footer section

Location of layout requirements that were completed:
-Flex was used for the navbar
-Grid was used for the main content 
-Floats were used in the footer

Extra CSS effects to check out:
-The search bar has a cool transition. The text colour changes too! Type something in to test it out.
-The buttons have a hover effect.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**HI @ikraamg, you have done very well:+1:. Just one change is required:**

Fix the search element within the navbar, it overshoots the navbar itself.

image

_**Kindly make this change and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by ikraamg** [comment]
Thanks, @mosesogwo . It seems like the bug was only present in Mozilla due to the flexbox child not working with flex:1 and needed to be changed to flex: auto. Very strange but I've learned to clearly define the flexbox.

**Comment by mosesogwo** [comment]
It's good you were able to debug the issue. You should get another review soon if you have submitted another code review request.

**Review by rOluochKe — APPROVED** [review]
Hello @ikraamg 
### Good job :clap: Having verified you made changes to the previous review and your project looks good, it passes the requirements. I, therefore, approve of it. Congratulations :boom: :100:
### You can merge to master and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
